import {
  TEMPLATE_HUB, TEMPLATE_TUTORIAL, TEMPLATE_ARENA, TEMPLATE_DUNGEON, TEMPLATE_DEV,
  TEMPLATE_FOREST_1, TEMPLATE_FOREST_2, TEMPLATE_FOREST_3,
  TEMPLATE_DESERT_1, TEMPLATE_DESERT_2, TEMPLATE_DESERT_3, TEMPLATE_DESERT_4,
  TEMPLATE_ICE_1, TEMPLATE_ICE_2, TEMPLATE_ICE_3, TEMPLATE_ICE_4, TEMPLATE_ICE_5,
  TEMPLATE_FOREST_BOSS, TEMPLATE_DESERT_BOSS, TEMPLATE_ICE_BOSS,
} from '../world/RoomTemplates';
import { ZoneConfig } from './ZoneConfig';

export const ZONE_REGISTRY: Record<string, ZoneConfig> = {
  dev: {
    id: 'dev', name: 'Developer Room', biome: 'dev',
    roomCount: 1, enemyPool: ['grunt', 'archer', 'juggernaut', 'cultist'],
    enemyHpMult: 1, enemyDmgMult: 1, enemyXpMult: 1,
    isEndless: false, nextZone: 'hub', availableFromHub: false,
    enemyCount: { min: 3, max: 6 },
    templates: [TEMPLATE_DEV],
  },
  hub: {
    id: 'hub', name: 'Town', biome: 'hub',
    roomCount: 1, enemyPool: [],
    enemyHpMult: 1, enemyDmgMult: 1, enemyXpMult: 1,
    isEndless: false, nextZone: null, availableFromHub: false,
    enemyCount: 0,
    templates: [TEMPLATE_HUB],
  },
  tutorial: {
    id: 'tutorial', name: 'Tutorial Glen', biome: 'tutorial',
    roomCount: 1, enemyPool: ['grunt'],
    enemyHpMult: 1.0, enemyDmgMult: 0.5, enemyXpMult: 0,
    isEndless: false, nextZone: 'hub', availableFromHub: true,
    enemyCount: { min: 3, max: 4 },
    templates: [TEMPLATE_TUTORIAL],
  },
  forest: {
    id: 'forest', name: 'Verdant Forest', biome: 'forest',
    roomCount: 4, enemyPool: ['grunt', 'archer'],
    enemyHpMult: 1.5, enemyDmgMult: 1.0, enemyXpMult: 1.0,
    isEndless: false, nextZone: 'hub', availableFromHub: true,
    enemyCount: { min: 9, max: 15 }, bossId: 'golem',
    templates: [TEMPLATE_FOREST_1, TEMPLATE_FOREST_2, TEMPLATE_FOREST_3, TEMPLATE_FOREST_BOSS],
  },
  desert: {
    id: 'desert', name: 'Scorched Desert', biome: 'desert',
    roomCount: 5, enemyPool: ['grunt', 'archer', 'juggernaut'],
    enemyHpMult: 2.5, enemyDmgMult: 1.3, enemyXpMult: 1.5,
    isEndless: false, nextZone: 'hub', availableFromHub: true,
    enemyCount: { min: 11, max: 20 },
    templates: [TEMPLATE_DESERT_1, TEMPLATE_DESERT_2, TEMPLATE_DESERT_3, TEMPLATE_DESERT_4, TEMPLATE_DESERT_BOSS],
  },
  ice: {
    id: 'ice', name: 'Frozen Wastes', biome: 'ice',
    roomCount: 6, enemyPool: ['grunt', 'archer', 'juggernaut', 'cultist'],
    enemyHpMult: 4.0, enemyDmgMult: 2.0, enemyXpMult: 2.5,
    isEndless: false, nextZone: 'hub', availableFromHub: true,
    enemyCount: { min: 13, max: 22 }, bossId: 'reaper',
    templates: [TEMPLATE_ICE_1, TEMPLATE_ICE_2, TEMPLATE_ICE_3, TEMPLATE_ICE_4, TEMPLATE_ICE_5, TEMPLATE_ICE_BOSS],
  },
  endless_dungeon: {
    id: 'endless_dungeon', name: 'Endless Dungeon', biome: 'endless',
    roomCount: 1, enemyPool: ['grunt', 'archer', 'juggernaut', 'cultist'],
    enemyHpMult: 1, enemyDmgMult: 1, enemyXpMult: 1,
    isEndless: 'procgen', nextZone: 'hub', availableFromHub: true,
    enemyCount: { min: 11, max: 15 },
    templates: [TEMPLATE_DUNGEON],
  },
  endless_arena: {
    id: 'endless_arena', name: 'Endless Arena', biome: 'endless',
    roomCount: 1, enemyPool: ['grunt', 'archer', 'juggernaut', 'cultist'],
    enemyHpMult: 1, enemyDmgMult: 1, enemyXpMult: 1,
    isEndless: 'wave', nextZone: 'hub', availableFromHub: true,
    enemyCount: { min: 7, max: 11 },
    templates: [TEMPLATE_ARENA],
  },
};
